version: '3.7'

services:
  user-ms:
    build:
      context: ./Backend/user-ms
      dockerfile: Dockerfile
    image: user-ms
    container_name: user-ms
    command: npm run dev-user
    volumes:
      - ./Backend/user-ms:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5001:5001"
    networks:
      - app-network

  categorie-ms:
    build:
      context: ./Backend/categorie-ms
      dockerfile: Dockerfile
    image: categorie-ms
    container_name: categorie-ms
    command: npm run dev-cat
    volumes:
      - ./Backend/categorie-ms:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5002:5002"
    depends_on:
      - user-ms
    networks:
      - app-network
networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local