export const GET_OFFRE_S = "GET OFFRE SUCCESS"
export const GET_OFFDEMS = "GET OFFRE & DEMANDES"
export const GET_ONE = "GET ONE OFFRE "
export const GET_OFFRE_F = "GET OFFRE FAILED"
export const OFFRE_ERROR = "ERROR OFFRE"

export const GET_DEMANDE_S = "GET DEMANDE BY USER"
export const GET_DEMANDE_F = "GET DEMANDE FAIL"
export const DEL_DEMANDE = "DEMANDE DELETED"
export const DEMANDE_ERROR = "ERROR DEMANDE"

