export const GET_ALL_USERS = 'GET ALL USERS';
export const GET_FAIL = 'GET_FAILURE';
export const USER_UP = 'USER_UPDATE';
export const USER_DEL = 'USER_DELETE';
export const USER_ERR = 'USERS_ERROR';
export const USER_REQ = 'USER REQUEST';
export const USER_UPDATE = 'USERS UPDATED';
export const USER_BAN = 'USER_BAN';
export const USER_BAN_FAIL = 'USER_BAN_FAIL';
