export const GET_OFFRE = "LOADING OFFRE"
export const GET_OFFRE_S = "GET OFFRE SUCCESS"
export const GET_OFFRE_F = "GET OFFRE FAILED"

export const GET_OFFDEMS = "LOADING OFFDEMS"
export const GET_OFFDEMS_S = "GET OFFDEMS SUCC"
export const GET_OFFDEMS_F = "GET OFFDDEMS FAILED"

export const OFFRE_ADDED = "ADD OFFRE DONE"
export const OFFRE_UPDATED = "UPDATE OFFRE DONE"
export const OFFRE_ARCHIVED = "ARCHIVE OFFRE DONE"
export const OFFRE_DELETED = "DELETE OFFRE DONE"
export const OFFRE_ERROR = "ERROR OFFRE"
