export const GET_OFFRE = "LOADING OFFRE"
export const GET_OFFRE_S = "GET OFFRE SUCCESS"
export const GET_OFFRE_F = "GET OFFRE FAILED"

export const GET_OFFREPUB = "LOADING OFFRE PUB "
export const GET_OFFREPUB_S = "GET OFFRE PUB SUCCESS"
export const GET_OFFREPUB_F = "GET OFFRE PUB FAILED"

export const GET_OFFDEMS = "LOADING OFFDEMS"
export const GET_OFFDEMS_S = "GET OFFDEMS SUCC"
export const GET_OFFDEMS_F = "GET OFFDDEMS FAILED"

export const LOADING_OFFRE = "LOADING ADD OFFRE"
export const OFFRE_ADDED = "ADD OFFRE DONE"
export const OFFRE_ADD_FAILED = "FAIL TO ADD OFFRE"

export const OFFRE_UPDATED = "UPDATE OFFRE DONE"
export const OFFRE_ARCHIVED = "ARCHIVE OFFRE DONE"
export const OFFRE_DELETED = "DELETE OFFRE DONE"
export const OFFRE_ERROR = "ERROR OFFRE"

export const DECRYPTING = "LOADING TO DECRYPTE"
export const DECRYPTING_S = "DECRYPTED SUCC"
export const DECRYPTING_F = "DECRYPTED FAIL"
